trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src/MyBackendApp/MyBackendApp.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/MyBackendApp/MyBackendApp.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'tests/MyBackendApp.Tests/MyBackendApp.Tests.csproj'